language: android
jdk: oraclejdk8

android:
  components:
  - tools
  - build-tools-28.0.3
  - android-27
  - extra-android-m2repository

before_install:
- yes | sdkmanager "platforms;android-27"
- chmod +x gradlew

#script:
#- ./gradlew build jacocoTestReport
#- ./gradlew test
#- ./gradlew testDebug


jobs:
  include:
  # build of app without any other task
  - stage: "Build"
    language: android
    script: ./gradlew assemble

# After Build, run all our tests first to ensure we wrote passing tests
  # run Release 1 Tests Only
  - stage: "Release 1 Tests"
    language: android
    script: ./gradlew test --tests="*.Release1.*"

  # run Release 2 Tests Only
  - stage: "Release 2 Tests"
    language: android
    script: ./gradlew test --tests="*.Release2.*"

  # run Release 3 Tests Only
  - stage: "Release 3 tests"
    language: android
    script: ./gradlew test --tests="*.Release3.*"

  # runs all tests
  - stage: "All Tests"
    language: android
    script: ./gradlew test testDebugUnitTest

  # static analysis using Android lint
  - stage: "Static Analysis"
    language: android
    script: ./gradlew lint

#  # runs static analysis
#  - stage: "Test Coverage"
#    language: android
#    script: ./gradlew build test createDebugCoverageReport


