language: android
jdk: oraclejdk8

android:
  components:
  - tools
  - build-tools-28.0.3
  - android-27
  - extra-android-m2repository

before_install:
- yes | sdkmanager "platforms;android-27"
- chmod +x gradlew

jobs:
  include:
# Build of app without any other task
  - stage: Build
    language: android
    script: ./gradlew assemble


# After Build, run all our tests first to ensure we wrote passing tests
  - stage: Test
    language: android
    name: "Release One Tests"
    script: ./gradlew testDebugUnitTest -Prelease="one"
  - script: ./gradlew testDebugUnitTest -Prelease="two"
    name: "Release Two Tests"
#  - script: ./gradlew testDebugUnitTest -Prelease="three"
#    name: "Release Three Tests"
  - script: ./gradlew test
    name: "All Tests"

# Static Analysis and Code Coverage
  - stage: Analyze
    language: android
    name: "Static Analysis"
    script: ./gradlew lint
  - script: ./gradlew jacocoTestReport
    name: "Test Coverage"
    after_success:
    - bash <(curl -s https://codecov.io/bash)
stages:
  - Build
  - Test
  - name: Analyze
    if: branch = master

