language: android
jdk: oraclejdk8

android:
 components:
    - tools
    - build-tools-28.0.3
    - android-27
    - extra-android-m2repository

before_install:
- yes | sdkmanager "platforms;android-27"
- chmod +x gradlew

script:
- ./gradlew build jacocoTestReport
- ./gradlew test
- ./gradlew testDebug
