language: android
jdk: oraclejdk8

android:
  components:
  - tools
  - build-tools-28.0.3
  - android-27
  - extra-android-m2repository

before_install:
- yes | sdkmanager "platforms;android-27"
- chmod +x gradlew
- export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"

jobs:
  include:
# Build and test in one script for faster builds
  - stage: Build And Test
    language: android
    script: ./gradlew assemble testDebugUnitTest 2>&1 | tee travisOutput.txt

#=============================================

# Build of app without any other task
  - stage: Build
    language: android
    script: ./gradlew assemble

# After Build, run all our tests first to ensure we wrote passing tests
  - stage: Test
    language: android
    name: "Release One Tests"
    script: ./gradlew testDebugUnitTest -Prelease="one"
  - script: ./gradlew testDebugUnitTest -Prelease="two"
    name: "Release Two Tests"
  - script: ./gradlew testDebugUnitTest -Prelease="three"
    name: "Release Three Tests"
  - script: ./gradlew test
    name: "All Tests"

# Static Analysis and Code Coverage
  - stage: Analyze
    language: android
    name: "Static Analysis"
    script: ./gradlew lint
  - script: ./gradlew jacocoTestReport
    name: "Test Coverage"


stages:
# Non-master builds (need speed)
  - name: Build And Test
    if: branch != master

# For master builds
  - name: Build
    if: branch = master
  - name: Test
    if: branch = master
  - name: Analyze
    if: branch = master

after_success:
  - echo "Success"
  - chmod 755 summarize-log.sh
  - ./summarize-log.sh

after_failure:
  - echo "Failure"
  - chmod 755 summarize-log.sh
  - ./summarize-log.sh
